// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transcription;

namespace Transcription.Migrations
{
    [DbContext(typeof(TranscriptionDbContext))]
    [Migration("20210502210247_RemovedRequired")]
    partial class RemovedRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Transcription.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Transcription.TransccriptionProgram", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProgramId");

                    b.ToTable("TransccriptionPrograms");
                });

            modelBuilder.Entity("Transcription.Employee", b =>
                {
                    b.HasOne("Transcription.TransccriptionProgram", null)
                        .WithMany()
                        .HasForeignKey("ProgramId");
                });
#pragma warning restore 612, 618
        }
    }
}
